Check for missing GHE_DATA_DIR variable in config
```
$ ./bin/ghe-backup
./bin/../share/github-backup-utils/ghe-backup-config: line 82: [: !=: unary operator expected
mkdir: : No such file or directory
```

These errors occur because `GHE_DATA_DIR` is not defined before running`ghe-backup-config`, causing it to throw errors.

```
$ ./share/github-backup-utils/ghe-backup-config
./share/github-backup-utils/ghe-backup-config: line 82: [: !=: unary operator expected
mkdir: : No such file or directory
Error: GHE_DATA_DIR  does not exist.
```

This change adds a test to ensure `GHE_DATA_DIR` is defined, else return an appropriate error.

```
$ ./bin/ghe-backup
Error: GHE_DATA_DIR not set in config file.
$ ./share/github-backup-utils/ghe-backup-config
Error: GHE_DATA_DIR not set in config file.
```